apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespace-turbonomic
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: 1-infrastructure
  source:
    path: payload/1-infrastructure/namespace/turbonomic/namespace
    repoURL: https://github.com/patrocinio/terraform-gitops-ocp-turbonomic
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences: []
